name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install dos2unix
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  code-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check code format
      run: cargo fmt -- --check

